import Head from "next/head";
import Image from "next/image";
import ReservationForm from "../components/ReservationForm";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Herd Label Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReservationForm />
    </>
  );
}
